# Generated by Django 6.1.1 on 2026-09-15 00:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('color_hex', models.CharField(default='#14464A', help_text='Color de identificación de la sede, ej. #14464A', max_length=7)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(blank=True, help_text='Ej. Piso 2 · Consultorio 3', max_length=150)),
                ('estado', models.CharField(choices=[('OK', 'Operativo'), ('REV', 'En revisión'), ('BAJA', 'De baja')], default='OK', max_length=4)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_qr', models.ImageField(blank=True, editable=False, null=True, upload_to='qr_codes/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='inventario.categoria')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='inventario.sede')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
