# Generated by Django 6.1.1 on 2026-09-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_seed_datos_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='cpu',
            field=models.CharField(blank=True, help_text='Ej. Intel i5 10ª generación', max_length=150),
        ),
        migrations.AddField(
            model_name='equipo',
            name='destino_sugerido',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='equipo',
            name='grupo_vigencia',
            field=models.CharField(blank=True, choices=[('A', 'Grupo A — Obsoleto (va a baja/reemplazo)'), ('B', 'Grupo B — Funcional (candidato a Linux Mint)'), ('C', 'Grupo C — Vigente (se mantiene)')], help_text='Clasificación según antigüedad y capacidad (solo aplica a PCs)', max_length=1),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, help_text='Ej. Dell Optiplex 3020', max_length=150),
        ),
        migrations.AddField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° de serie / etiqueta'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ram_gb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM (GB)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sistema_operativo',
            field=models.CharField(blank=True, help_text='Ej. Windows 10, Linux Mint', max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='software_asociado',
            field=models.CharField(blank=True, help_text='Ej. Consola CareRay + PACS dicomPACS', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Área/ubicación, ej. Piso 2 · Consultorio 3', max_length=150),
        ),
    ]
